name: Test and Build  # Name of the workflow

on:  # Specifies when the workflow should be triggered
  push:  # Trigger the workflow on every push
    branches:  # Specifies which branches to trigger the workflow
      - '*'  # Applies to all branches
  pull_request:  # Also trigger on pull requests
    branches:
      - '*'  # Applies to all branches

jobs:
  build-and-test:  # Name of the job
    runs-on: ubuntu-latest  # Specifies the type of runner (latest Ubuntu VM)

    steps:  # Series of tasks executed as part of the job
      - name: Checkout code  # Check out the repository code
        uses: actions/checkout@v2

      - name: Set up Python  # Sets up the Python environment
        uses: actions/setup-python@v2
        with:
          python-version: '3.11'  # Defines the Python version

      - name: Install dependencies  # Install required Python packages
        run: |
          python -m pip install --upgrade pip
          pip install -r 23/requirements.txt  # Install dependencies from the requirements.txt in the 23 directory

      - name: Run unit tests  # Execute unit tests
        run: python -m unittest discover 23/tests  # Discover and run unit tests in the 23/tests directory

      # Include additional steps here if necessary, like building a Docker image
